### ISSUE TITLE
cannot unmarshal array into Go struct field Model.items.allowCommercialUse of type string

### ISSUE THREAD

**Issue by drgrib** [jkawamoto/go-civitai#6]
Running this example from the README
```go
package main

import (
	"context"
	"log"

	"github.com/go-openapi/swag"
	"github.com/jkawamoto/go-civitai/client"
	"github.com/jkawamoto/go-civitai/client/operations"
)

func ExampleGetModels() {
	ctx := context.Background()

	res, err := client.Default.Operations.GetModels(
		operations.NewGetModelsParamsWithContext(ctx).WithLimit(swag.Int64(3)))
	if err != nil {
		log.Fatal(err)
	}

	for _, v := range res.Payload.Items {
		log.Println(v.Name, v.ID, v.Tags)
	}
}

func main() {
	ExampleGetModels()
}
```
Causes this error
```
2024/09/18 06:16:58 json: cannot unmarshal array into Go struct field Model.items.allowCommercialUse of type string
exit status 1
```
Looks like the schema is out of date and needs to be updated.

**Comment by drgrib** [comment]
This is an issue with the documentation itself, which I discovered and reported here https://github.com/civitai/civitai/issues/1376

**Comment by drgrib** [comment]
Actually, even `createdAt` and `updatedAt` have been replaced with `publishedAt`. The documentation appears to be severely outdated.

**Comment by jkawamoto** [comment]
Thank you for reporting this problem. I remember their documentation was not frequently updated, so I had to refer to their source code to find accurate information.

 I'll update this package to at least fix this error soon.

**Comment by jkawamoto** [comment]
Hopefully, v0.2.2 fixes this issue. If not, please reopen.

**Comment by jkawamoto** [comment]
I had read their TypeScript code, such as https://github.com/civitai/civitai/blob/main/src/pages/api/v1/models/index.ts, because, unfortunately, their documentation doesn't provide complete information on data types. However, this process was time-consuming.

This time, I collected some samples using `curl`. While this approach may result in missing some attributes, at least my code is functional.
